apiVersion: apps/v1
kind: Deployment
metadata:
  name: Office
  labels:
    app: Office
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Office
  template:
    metadata:
      labels:
        app: Office
    spec:
      containers:
        - name: Office
          image: username/Office:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
